### ISSUE TITLE
Getting error with expression evaluating a string

### ISSUE THREAD

**Issue by TurboCooler** [lhelwerd/expression-parser#1]
For my sample code, I have the following:

import expression
parser = expression.Expression_Parser()
# this line below
print(parser.parse("( 1 < 1) and ('AB' == 'US') or 'userval1' != 'UPS'"))
# returns this error
( 1 < 1) and ('AB' == 'US') or 'userval1' != 'UPS'
                 ^
SyntaxError: Node Str(s='AB') not allowed

#The line below works as pure python
print(( 1 < 1 and 'US' == 'US') or 'userval1' != 'UPS') 

Does the code not allow the evaluation of strings?

**Comment by lhelwerd** [comment]
Correct, the parser does not accept string literals. However, you can inject string values into the parser environment using the `variables` parameter in the constructor. This allows you to compare user-provided values and constants within an expression. For example:

```python
import expression
userval1 = "userval1"
parser = expression.Expression_Parser(variables={"foo": "US",
                                                 "bar": "AB",
                                                 "baz": "UPS",
                                                 "userval1": userval1})
print(parser.parse("( 1 < 1) and (bar == foo) or userval1 != baz"))
```

Not allowing strings is mostly a design choice as it ensures that the accepted expressions are clean and simple. You are welcome to extend the parse to accept string/unicode literals if you require it.
